spring.application.name=Payments
spring.jpa.hibernate.ddl-auto=update

# Configurações do H2 Console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.h2.console.settings.web-allow-others=true

# Configuração do Banco de Dados Relacional H2 (Em Memória)
spring.datasource.url=jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
spring.datasource.username=sa
spring.datasource.password=password
spring.datasource.driverClassName=org.h2.Driver

# Configurações do Spring Boot Actuator & Observabilidade
management.endpoints.web.exposure.include=health,info,metrics,prometheus
management.endpoint.health.show-details=always
management.metrics.tags.application=${spring.application.name}

# Padrão de Logs Estruturados
logging.level.root=INFO
logging.level.com.paypic.Payments=DEBUG
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n
